# Generated by Django 4.2.7 on 2024-12-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0013_alter_course_course_code_alter_course_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['version', 'seq_num']},
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course_code',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_content', to='fp_courses.course'),
        ),
    ]
