# Generated by Django 4.2.7 on 2024-12-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0014_survey'),
        ('fp_courses', '0015_delete_coursecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=3)),
                ('seq_num', models.IntegerField(default=10)),
                ('content_type', models.IntegerField(choices=[(0, 'Article'), (1, 'Quiz')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_article', to='fp_blog.article')),
                ('course_code', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_contents', to='fp_courses.course')),
            ],
            options={
                'ordering': ['version', 'seq_num'],
                'unique_together': {('course_code', 'version', 'seq_num')},
            },
        ),
    ]
